version: '3.5'
services:
  rmqnamesrv-a:
    image: rocketmqinc/rocketmq:latest
    container_name: rmqnamesrv-a
    ports:
      - 9876:9876
    volumes:
      - ./rocketmq/logs/nameserver-a:/root/logs
      - ./rocketmq/store/nameserver-a:/root/store
    command: sh mqnamesrv
    networks:
      rmq:
        aliases:
          - rmqnamesrv-a

  rmqnamesrv-b:
    image: rocketmqinc/rocketmq:latest
    container_name: rmqnamesrv-b
    ports:
      - 9877:9876
    volumes:
      - ./rocketmq/store/nameserver-b:/root/store
      - ./rocketmq/logs/nameserver-b:/root/logs
    command: sh mqnamesrv
    networks:
      rmq:
        aliases:
          - rmqnamesrv-b

  rmqbroker-a:
    image: rocketmqinc/rocketmq:latest
    container_name: rmqbroker-a
    ports:
      - 10911:10911
    volumes:
      - ./rocketmq/logs/broker-a:/root/logs
      - ./rocketmq/store/broker-a:/root/store
      - ./rocketmq/broker-a.conf:/opt/rocketmq-4.4.0/conf/broker.conf
    environment:
      TZ: Asia/Shanghai
      NAMESRV_ADDR: "rmqnamesrv-a:9876"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
    command: sh mqbroker -c /opt/rocketmq-4.4.0/conf/broker.conf autoCreateTopicEnable=true &
    links:
      - rmqnamesrv-a:rmqnamesrv-a
      - rmqnamesrv-b:rmqnamesrv-b
    networks:
      rmq:
        aliases:
          - rmqbroker-a

  rmqbroker-a-s:
    image: rocketmqinc/rocketmq:latest
    container_name: rmqbroker-a-s
    ports:
      - 10912:10911
    volumes:
      - ./rocketmq/logs/broker-a-s:/root/logs
      - ./rocketmq/store/broker-a-s:/root/store
      - ./rocketmq/broker-a-s.conf:/opt/rocketmq-4.4.0/conf/broker.conf
    environment:
      TZ: Asia/Shanghai
      NAMESRV_ADDR: "rmqnamesrv-a:9876"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
    command: sh mqbroker -c /opt/rocketmq-4.4.0/conf/broker.conf autoCreateTopicEnable=true &
    links:
      - rmqnamesrv-a:rmqnamesrv-a
      - rmqnamesrv-b:rmqnamesrv-b
    networks:
      rmq:
        aliases:
          - rmqbroker-a-s

  rmqbroker-b:
    image: rocketmqinc/rocketmq:latest
    container_name: rmqbroker-b
    ports:
      - 10913:10911
    volumes:
      - ./rocketmq/logs/broker-b:/root/logs
      - ./rocketmq/store/broker-b:/root/store
      - ./rocketmq/broker-b.conf:/opt/rocketmq-4.4.0/conf/broker.conf
    environment:
      TZ: Asia/Shanghai
      NAMESRV_ADDR: "rmqnamesrv-a:9876"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
    command: sh mqbroker -c /opt/rocketmq-4.4.0/conf/broker.conf autoCreateTopicEnable=true &
    links:
      - rmqnamesrv-a:rmqnamesrv-a
      - rmqnamesrv-b:rmqnamesrv-b
    networks:
      rmq:
        aliases:
          - rmqbroker-b

  rmqbroker-b-s:
    image: rocketmqinc/rocketmq:latest
    container_name: rmqbroker-b-s
    ports:
      - 10914:10911
    volumes:
      - ./rocketmq/logs/broker-b-s:/root/logs
      - ./rocketmq/store/broker-b-s:/root/store
      - ./rocketmq/broker-b-s.conf:/opt/rocketmq-4.4.0/conf/broker.conf
    environment:
      TZ: Asia/Shanghai
      NAMESRV_ADDR: "rmqnamesrv-a:9876"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
    command: sh mqbroker -c /opt/rocketmq-4.4.0/conf/broker.conf autoCreateTopicEnable=true &
    links:
      - rmqnamesrv-a:rmqnamesrv-a
      - rmqnamesrv-b:rmqnamesrv-b
    networks:
      rmq:
        aliases:
          - rmqbroker-b-s

  rmqconsole:
    image: styletang/rocketmq-console-ng:latest
    container_name: rmqconsole
    ports:
      - 6080:8080
    environment:
      JAVA_OPTS: -Drocketmq.namesrv.addr=rmqnamesrv-a:9876;rmqnamesrv-b:9877 -Dcom.rocketmq.sendMessageWithVIPChannel=false
    networks:
      rmq:
        aliases:
          - rmqconsole

networks:
 rmq:
   name: rmq
   driver: bridge
